name: CommandBridge
version: ${project.version}
main: cn.southplex.commandbridge.CommandBridgeSpigot
authors: [ jingwenMC ]
description: Send bukkit command to bungee
website: www.jingwenmc.top
softdepend:
  - MQEasy
commands:
  sendcmd:
    description: Send cmd to bungee, permission required.
  sendcmdtoserver:
    description: Send cmd to another server, permission required.
    aliases:
      - scts
      - sctsbukkit
permissions:
  commandbridge.spigot.send:
    description: Allow player send command to bungeecord
    default: op